### ISSUE TITLE
Question about the RIBES.py

### ISSUE THREAD

**Issue by yoori000** [nttcslab-nlp/RIBES#1]
When checking 169~179  lines of the RIBES.py file, check the window of the hypothesis sentence, and when the overlapping count is 1 for both ref and hyp, add index to the intlist.

This is done when ref.count and hyp.count are not 1-1 mapping.

By the way, isn't it necessary to add index to the intlist even when the overlapping count is 0?

In the example I tested, the specific word is n-n mapping, but the overlapping count is 0, so I think it is strange because it cannot be added to the intlist.
(In particular, I don't understand adding index to intlist only when overlapping count is 1.)

I would appreciate it if you could explain it.

**Comment by MorinoseiMorizo** [comment]
@ksudoh could you answer the question please?

**Comment by ksudoh** [comment]
Hi,
This part is from the original in-house code and implements the creation of a word order list shown on:
- the upper-right paragraph on page 946 of our first conference paper https://www.aclweb.org/anthology/D10-1092.pdf
- Algorithm 1 at the bottom of page 427 of our journal paper (in Japanese) https://www.jstage.jst.go.jp/article/jnlp/21/3/21_421/_pdf/-char/ja

Regarding the question, this part just skips any non-overlapping words in line 158.

**Comment by MorinoseiMorizo** [comment]
Since more than a month has passed, I will close this issue.
If you still have a question, please feel free to re-open.
@ksudoh Thank you for the answer!
